[smtp_printer]
server = "smtp.gmail.com"
port = 587
# security = "tls"
username = "${smtp_login}"
password = "${smtp_passwd}"
from_email = "${smtp_from_email}"
to_emails = "${smtp_to_emails}"


[[services]]
category = "BTC"
endpoint = "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd&include_24hr_change=true"

[services.headers]
x-cg-demo-api-key = "${coingecko_api_key}"

[services.fields]
price = "$.bitcoin.usd"
price_change_24h = "$.bitcoin.usd_24h_change"

[[services]]
category = "ETH"
endpoint = "https://api.coingecko.com/api/v3/simple/price?include_24hr_change=true&vs_currencies=usd&ids=eth0"

[services.headers]
x-cg-demo-api-key = "${coingecko_api_key}"

[services.fields]
price = "$.eth0.usd"
price_change_24h = "$.eth0.usd_24h_change"

[[services]]
category = "SOL"
endpoint = "https://api.coingecko.com/api/v3/simple/price?include_24hr_change=true&vs_currencies=usd&ids=solana"

[services.headers]
x-cg-demo-api-key = "${coingecko_api_key}"

[services.fields]
price = "$.solana.usd"
price_change_24h = "$.solana.usd_24h_change"

[[services]]
category = "BNB"
endpoint = "https://api.coingecko.com/api/v3/simple/price?include_24hr_change=true&vs_currencies=usd&ids=binancecoin"

[services.headers]
x-cg-demo-api-key = "${coingecko_api_key}"

[services.fields]
price = "$.binancecoin.usd"
price_change_24h = "$.binancecoin.usd_24h_change"

[[services]]
category = "CCJ (Cameco)"
endpoint = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=CCJ&apikey=${alpha_vantage_api_key}"

[services.reference_fields]
last_quotation_date = "$['Meta Data']['3. Last Refreshed']"

[services.fields]
date = "$['Meta Data']['3. Last Refreshed']"
open = "$['Time Series (Daily)']['${last_quotation_date}']['1. open']"
high = "$['Time Series (Daily)']['${last_quotation_date}']['2. high']"
low = "$['Time Series (Daily)']['${last_quotation_date}']['3. low']"
close = "$['Time Series (Daily)']['${last_quotation_date}']['4. close']"
volume = "$['Time Series (Daily)']['${last_quotation_date}']['5. volume']"

[[services]]
category = "PSLV (Sprott Physical Silver Trust)"
endpoint = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=PSLV&apikey=${alpha_vantage_api_key}"

[services.reference_fields]
last_quotation_date = "$['Meta Data']['3. Last Refreshed']"

[services.fields]
date = "$['Meta Data']['3. Last Refreshed']"
open = "$['Time Series (Daily)']['${last_quotation_date}']['1. open']"
high = "$['Time Series (Daily)']['${last_quotation_date}']['2. high']"
low = "$['Time Series (Daily)']['${last_quotation_date}']['3. low']"
close = "$['Time Series (Daily)']['${last_quotation_date}']['4. close']"
volume = "$['Time Series (Daily)']['${last_quotation_date}']['5. volume']"



